### ISSUE TITLE
Split content out into its own repo(s)

### ISSUE THREAD

**Issue by vonkow** [karst-club/karst#16]
It would be cool if the content was at the top level of the project, but it would be even cooler if it was in a separate repo that deployed to s3 or memcached or something and was read by the API 

This would open up the possibility of having multiple content repos for rules, characters/campaigns, and secret GM notes.

**Comment by sarah-johnson** [comment]
I like this. I do want to make sure that a new person can still easily clone, build and run the entire project with ease, that is my only hesitation.

While we're at it, I've been questioning the validity of needing an API server to be running at all.

With the way the site is currently designed, it would be more reasonable to just have a deploy script that creates JSON manifests which can be read by the react app as flat files, and get rid of the flask app completely.

**Comment by vonkow** [comment]
Definitely agree on the ease of use requirement. I think we could have some mechanism of automatically fetching the Rulebook and Worldbook content in a setup script which could also create an empty Story repo or something similar?

We could probably just make everything static, but an API server could still be useful for being able to post to discord, especially if it was a hybrid server and bot. 

Relatedly, I was just looking at this RPG bot for inspiration https://github.com/TheSamLloyd/Elbie/

**Comment by sarah-johnson** [comment]
https://github.com/karst-club/karst/pull/23 moves content to the top level of the project at least.

**Comment by vonkow** [comment]
So, I think a way we could do this is configure the part that walks the filesystem tree to generate content to look at an array of file paths passed in as an environment variable. Then, we could move the content out into separate repos that are deployed to the same box as the app. I would imagine that we could start with 3 content repos, the rules, stories, and narrators secrets.

This would also let us deploy new content without having downtime as uwsgi cycles, since the deploy is just an `scp` or `git pull` of static resources. (Browsers would still have to refresh for content, but we could fix that later).

**Comment by sarah-johnson** [comment]
Now that we have migrated to Gatsby I am not sure where or how to take this issue forward, if at all.

**Comment by sarah-johnson** [comment]
For now our needs are met. We can reopen this at a future date if we decide we want to incorporate authentication into the app. https://www.gatsbyjs.com/tutorial/authentication-tutorial/
