### ISSUE TITLE
The Karst API should not DangerouslySetInnerHTML

### ISSUE THREAD

**Issue by sarah-johnson** [karst-club/karst#3]
We don't want the Flask app to serve any HTML. We would prefer it to pass us structured JSON including markdown blobs that we will render in the front end.

Requirements:
 - Must be able to embed references to Tables which will also be described as "page metadata" JSON blobs.

There are several possible solutions to look into:
 - Markdown (possible libraries: showdown, react-showdown, and 
 - MDX (https://mdxjs.com/)

**Comment by sarah-johnson** [comment]
https://mdxjs.com/getting-started/create-react-app

**Comment by sarah-johnson** [comment]
https://www.rover.com/design-system/components/heading/overview/

**Comment by vonkow** [comment]
The PR I put up for this only handles singular blobs of markdown, not structured json with markdown and csv fragments interleaved, but I believe that we can use custom MDX components on the frontend to achieve the sorting and stuff that we want out of tabular data.
