### ISSUE TITLE
XP Thresholds for Levels, and Leveling Rules/Procedures

### ISSUE THREAD

**Issue by sarah-johnson** [karst-club/karst#35]
* How much XP is needed for the first few levels?
* Give some concrete examples of how/when XP is earned
* To the extent that these rules can be codified, let's do so. Perhaps a CLI to walk someone through leveling their character, or a unit test to ensure that a character sheet's level/XP data is valid.

**Comment by vonkow** [comment]
As with most rules, I'm basically cribbing from B/X D&D and then modifying as appropriate. I was thinking characters should level like [fighters](https://oldschoolessentials.necroticgnome.com/srd/index.php/Fighter) when it comes to XP per level. I'll add this to the character section after fleshing out how you actually gain the level once you have the XP (maybe you have to sleep on it or something?).

As far as getting said XP, characters gain XP from recovering coins and other loot on a 1 for 1 Coin -> XP basis and from overcoming monsters (not necessarily defeating them in combat).
